name: Auto-Fix & Open PR — Re-enable strict builds

on:
  workflow_dispatch: {} # run manually from Actions tab

permissions:
  contents: write # allows committing and creating PRs inside this repo
  pull-requests: write
  issues: write
  actions: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (best-effort)
        run: |
          npm ci || true

      - name: Run ESLint auto-fix (safe fixes)
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx --fix || true

      - name: Ensure required files (next.config.ts, apphosting.yaml, CI workflow)
        run: |
          # write strict next.config.ts
          cat > next.config.ts <<'EOF'
// next.config.ts (enforced by CI)
import { NextConfig } from 'next';

const nextConfig: NextConfig = {
  reactStrictMode: true,
  typescript: {
    // Require TypeScript to be error-free for production builds
    ignoreBuildErrors: false,
  },
  eslint: {
    // Require ESLint to be error-free for production builds
    ignoreDuringBuilds: false,
  },
};

export default nextConfig;
EOF

          # apphosting.yaml for Firebase Studio
          cat > apphosting.yaml <<'EOF'
runtime: nodejs18
env: production
EOF

          # Add CI workflow file
          mkdir -p .github/workflows
          cat > .github/workflows/ci.yml <<'EOF'
name: CI — Typecheck & Lint & Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run Next.js build
        run: npm run build
EOF

      - name: Commit changes and create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: chore: re-enable strict Next.js type/lint checks and add CI (auto)
          branch: fix/ci-enforce-build-checks
          title: Enforce TypeScript & ESLint in CI and re-enable strict Next.js build checks
          body: |
            This PR was created automatically by a workflow.

            Changes included:
            - next.config.ts: set typescript.ignoreBuildErrors=false and eslint.ignoreDuringBuilds=false
            - apphosting.yaml: minimal Firebase hosting config (runtime nodejs18)
            - .github/workflows/ci.yml: CI workflow to run tsc, eslint, and next build on PRs and pushes to main
            - ESLint auto-fixes applied where safe

            Please review the changes, run the Typescript & build locally if needed, and merge when ready.
          labels: automated, ci
